apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: default
  labels:
    name: default-backend
    app: csingress
spec:
  ports:
  - port: 80
    targetPort: 10254
  selector:
    app: csingress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: csingress
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csingress
    spec:
      containers:
      - name: csingress
        image: IMAGE
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          timeoutSeconds: 5
        command: ["./csingress"]
        args: ["--default-backend-service", "default/default-http-backend"]
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
